name: check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.0]

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: check
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: run check
